name: ck-propel1-test
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
      - /var/www/vendor  # Exclude vendor from volume mount for performance
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    environment:
      - PHP_IDE_CONFIG=serverName=propel-dev
    working_dir: /var/www
    command: tail -f /dev/null
    #user: "1000:1000"  # Using host user ID to avoid permission issues

  mysql:
    image: mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
      - ./test:/docker-entrypoint-initdb.d
    networks:
      - app-network
    ports:
      - "3308:3306"  # Expose MySQL port for external connections
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot" ]
      timeout: 5s
      retries: 10
      interval: 10s

  #Add a web server for testing web-based functionality
  nginx:
    image: nginx:alpine
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:82"
    depends_on:
      - php
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
