name: ck-propel1-test
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
    networks:
      - app-network
    command: tail -f /dev/null

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php7
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./:/var/www
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
